### ISSUE TITLE
Consider replacing Flask-User

### ISSUE THREAD

**Issue by PaluMacil** [ChadevPython/beer-tracker#4]
Flask-User pulls in Pycrypto somewhat unnecessarily since Flask hash functions (werkzeug.security.generate_password_hash()) use PBKDF2 by default since May 2013 anyway. Eliminating this would simplify the pip install process--especially for Windows where binary wheels aren't provided for this. Additionally, I'm not sure Flask User is necessary. You can add a simple wrapper like Miguel Grinberg did in https://github.com/miguelgrinberg/flasky/blob/master/app/decorators.py

That's not to say that Flask-User is useless, but it is more than we need. On the plus side, it gives a lot of additional decorators, but it hasn't recently accepted any pull requests to fix deprecated .ext. imports, so that is concerning as well.

**Comment by juzten** [comment]
I am using Flask User for a hand full of features that we will need: registration, login/logout, roles, password management, registration emails, some of the decorators, etc..

This should keep the user management system where we don't have to do much. I've looked at Flask-User issues and it seems there is a pull request to fix the ext imports updates and hopefully it'll be merged soon as the latest activity on it was a day or 2 ago. 

I'm opening an issue related to getting setup with vagrant to keep install issues a minimum. see #6

**Comment by PaluMacil** [comment]
Alrighty. Sounds good. I just wanted to gather opinions. :)
