### ISSUE TITLE
Remove Flask Alembic

### ISSUE THREAD

**Issue by PaluMacil** [ChadevPython/beer-tracker#5]
I'd like to hear thoughts before I submit a PR, but migrations seem, to me, to be too complicated for a simple app and might be best eliminated for now. However, I would also be happy to dig in if someone is able to do a lesson on migrations and how they work.

**Comment by juzten** [comment]
@PaluMacil As simple as this project is, I feel that migrations are still needed as it is hard to tell when the database structure will change. Flask Alembic will help everyone keep their local database in sync with any changes that are made as well. I can go over migrations soon with the group, either at one of the future google hangouts or at the next python meetup. 

If you're happy with this, feel free to close this issue, or we can close it after I go over it with the group.

**Comment by PaluMacil** [comment]
sounds good... in my work life (currently SQL Server and .NET) I tend to manually write a large TSQL script that rolls out a database change and migrates data, and that usually means manually writing a script rolling back too. Even though the languages and libraries are different, learning about migrations will probably help me immensely and I look forward to it. Looking at all the files involved which Alembic produces has been intimidating though--which is why I've put it off--so I'll try to look at Alembic again so that I can also have some questions prepared before the lesson.

**Comment by juzten** [comment]
If you manually write db migrations, you're going to love the simplicity of Alembic!
The basic workflow:
- update a model, say adding a field to the User model
- run `python manage.py db migrate -m 'migration comment'`
  that creates the migration code automatically
- then run `python manage.py db upgrade`
  that runs the migration against the database and you're done

**Comment by PaluMacil** [comment]
ohhhhhhhhh.... so.... I tried to learn it by studying all the boilerplate stuff it generates. I didn't read a tutorial. So... I thought it was a lot more complex than that. :smile: Gosh.... so many hours of work writing migrations...

**Comment by juzten** [comment]
I'll be sure to write it out in our docs also just so we have it documented
